/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iccconstruct.labsystem.view.panels;

import com.iccconstruct.labsystem.controller.ControllerFactory;
import com.iccconstruct.labsystem.controller.custom.LoginHistoryController;
import com.iccconstruct.labsystem.dto.LoginHistoryDTO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dilini Peiris
 */
public class LoginHistory extends javax.swing.JPanel {

    LoginHistoryController historyController;
    
    public LoginHistory() {
        try {
            initComponents();
            historyController = (LoginHistoryController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.LOGIN);
            setHistory();
        } catch (Exception ex) {
            Logger.getLogger(LoginHistory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoginHis = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(560, 560));

        tblLoginHis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Login Entry", "Username", "Name", "Log  In Time", "Log Out Time"
            }
        ));
        jScrollPane1.setViewportView(tblLoginHis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLoginHis;
    // End of variables declaration//GEN-END:variables

    private void setHistory() throws Exception {
        ArrayList<LoginHistoryDTO> all = historyController.getAll();
        if(all==null){
            JOptionPane.showMessageDialog(LoginHistory.this, "There are no login details to display", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        DefaultTableModel dtm =(DefaultTableModel) tblLoginHis.getModel();
        dtm.setRowCount(0);
        for (LoginHistoryDTO all1 : all) {
            Object[] rowData = {all1.getLogID(),all1.getdTO().getUsername(),all1.getdTO().getFname()+all1.getdTO().getLname(),all1.getLogIN(),all1.getLogOut()};
            dtm.addRow(rowData);
        }
    }
}
