/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iccconstruct.labsystem.view;

import com.iccconstruct.labsystem.controller.ControllerFactory;
import com.iccconstruct.labsystem.controller.custom.LoginHistoryController;
import com.iccconstruct.labsystem.view.panels.DatabaseBackup;
import com.iccconstruct.labsystem.view.panels.LoginHistory;
import com.iccconstruct.labsystem.view.panels.MixDesignInfo;
import com.iccconstruct.labsystem.view.panels.MixDesignPDFs;
import com.iccconstruct.labsystem.view.panels.SystemUsers;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dilini Peiris
 */
public class AdminHome extends javax.swing.JFrame {

    LoginHistoryController historyController;

    public AdminHome() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(Dashboard.image.getImage());
        setTitle("ICC - Lab System - Administrator");
        historyController = (LoginHistoryController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.LOGIN);
        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                String[] buttons = new String[]{"Yes", "No", "Log Out"};
                int confirm = JOptionPane.showOptionDialog(
                        AdminHome.this, "Are you sure you want to close the Application? Any unsaved data will be lost!",
                        "Exit Confirmation", 0,
                        JOptionPane.QUESTION_MESSAGE, null, buttons, buttons[1]);
                System.out.println(confirm);
                if (confirm == 0) {
                    System.exit(0);
                } else if (confirm == 2) {
                    try {
                        System.out.println(Dashboard.history);
                        boolean update = historyController.update(Dashboard.history);

                        if (update) {
                            AdminHome.this.dispose();
                            Dashboard d = new Dashboard();
                            d.setNewLogin();
                            d.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(AdminHome.this, "Cannot Log Out", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnMixDesigns = new javax.swing.JButton();
        btnViewUsers = new javax.swing.JButton();
        btnLoginHis = new javax.swing.JButton();
        btnDBbackup = new javax.swing.JButton();
        btnCreateMix = new javax.swing.JButton();
        btnManagePDF = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnMixDesignHistory = new javax.swing.JButton();
        btnMyMixdesigns = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 560));

        pnlContainer.setMinimumSize(new java.awt.Dimension(560, 560));
        pnlContainer.setPreferredSize(new java.awt.Dimension(560, 560));
        pnlContainer.setRequestFocusEnabled(false);
        pnlContainer.setLayout(new java.awt.CardLayout());

        jButton7.setText("My Account");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.setOpaque(false);

        btnMixDesigns.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMixDesigns.setText("Mix Designs");
        btnMixDesigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMixDesignsActionPerformed(evt);
            }
        });

        btnViewUsers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewUsers.setText("System Users");
        btnViewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUsersActionPerformed(evt);
            }
        });

        btnLoginHis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLoginHis.setText("Login History");
        btnLoginHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginHisActionPerformed(evt);
            }
        });

        btnDBbackup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDBbackup.setText("Database Backup/Restore");
        btnDBbackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBbackupActionPerformed(evt);
            }
        });

        btnCreateMix.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreateMix.setText("Create Mix Design Form");
        btnCreateMix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMixActionPerformed(evt);
            }
        });

        btnManagePDF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManagePDF.setText("Mix Design PDFs");
        btnManagePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePDFActionPerformed(evt);
            }
        });

        btnMixDesignHistory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMixDesignHistory.setText("Adjusted Mix-Design History");
        btnMixDesignHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMixDesignHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(btnManagePDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMixDesigns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateMix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLoginHis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDBbackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMixDesignHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator2)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnManagePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnMixDesigns, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateMix, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoginHis, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMixDesignHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDBbackup, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMyMixdesigns.setText("My Adjusted Mix Designs");
        btnMyMixdesigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyMixdesignsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMyMixdesigns)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMyMixdesigns, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMixDesignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMixDesignsActionPerformed
        navigate(0);
    }//GEN-LAST:event_btnMixDesignsActionPerformed

    private void btnViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUsersActionPerformed
        navigate(1);
    }//GEN-LAST:event_btnViewUsersActionPerformed

    private void btnLoginHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginHisActionPerformed
        navigate(2);
    }//GEN-LAST:event_btnLoginHisActionPerformed

    private void btnDBbackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBbackupActionPerformed
        navigate(4);
    }//GEN-LAST:event_btnDBbackupActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new UserProfile().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnCreateMixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMixActionPerformed
        new MixDesignForm().setVisible(true);
    }//GEN-LAST:event_btnCreateMixActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(AdminHome.this, "Are you sure you want to Log out?");
        if (showConfirmDialog == 0) {
            try {
                boolean update = historyController.update(Dashboard.history);

                if (update) {
                    AdminHome.this.dispose();
                    Dashboard d = new Dashboard();
                    d.setNewLogin();
                    d.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(AdminHome.this, "Cannot Log Out", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnManagePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePDFActionPerformed
        navigate(3);
    }//GEN-LAST:event_btnManagePDFActionPerformed

    private void btnMixDesignHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMixDesignHistoryActionPerformed
        new MixDesignHistory().setVisible(true);
    }//GEN-LAST:event_btnMixDesignHistoryActionPerformed

    private void btnMyMixdesignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyMixdesignsActionPerformed
        new MyAdjustedMixDesigns().setVisible(true);
    }//GEN-LAST:event_btnMyMixdesignsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateMix;
    private javax.swing.JButton btnDBbackup;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLoginHis;
    private javax.swing.JButton btnManagePDF;
    private javax.swing.JButton btnMixDesignHistory;
    private javax.swing.JButton btnMixDesigns;
    private javax.swing.JButton btnMyMixdesigns;
    private javax.swing.JButton btnViewUsers;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlContainer;
    // End of variables declaration//GEN-END:variables

    private void navigate(int i) {
        pnlContainer.removeAll();
        System.out.println("navigating -- removed all");

        switch (i) {
            case 0:
                pnlContainer.add(new MixDesignInfo());
                System.out.println("mixdesign added");
                break;
            case 1:
                pnlContainer.add(new SystemUsers());
                System.out.println("users added");
                break;
            case 2:
                pnlContainer.add(new LoginHistory());
                System.out.println("log his added");
                break;
            case 3:
                pnlContainer.add(new MixDesignPDFs());
                System.out.println("manage pdf added");
                break;
            case 4:
                pnlContainer.add(new DatabaseBackup());
                System.out.println("backup added");
                break;

        }

        pnlContainer.updateUI();

    }
}
